# config.yaml - MINE 训练配置
data:
  train_csv: "/root/autodl-tmp/datasets/ljspeech/features/csv/mel_complex_csv/train.csv"
  valid_csv: "/root/autodl-tmp/datasets/ljspeech/features/csv/mel_complex_csv/valid.csv"
  test_csv: "/root/autodl-tmp/datasets/ljspeech/features/csv/mel_complex_csv/test.csv"
  features_dir: "/root/autodl-tmp/datasets/ljspeech/features/csv/mel_complex_csv"
  segment_length: 200       # 裁剪的序列长度
  normalization: 'standard' # Float 特征归一化: none, minmax, standard, robust

model:
  # --- 选择网络类型 ---
  # network_type: 'float'     # 如果 x 和 y 都是 float 特征
  network_type: 'float'     # 如果 x 是 index (long), y 是 float

  # --- 如果 network_type is 'index', 需要下面两个参数 ---
  vocab_size: 5000          # 示例: X 的词汇表大小 (!!!根据你的数据修改!!!)
  embedding_dim: 256        # 示例: X 的 Embedding 维度

  # --- 通用 MLP 参数 ---
  hidden_dims: [16] # 网络隐藏层维度
  activation: 'relu'        # 激活函数: relu, leaky_relu, elu
  batch_norm: True          # 是否使用 BatchNorm
  dropout: 0.1              # Dropout 率 (0 表示不用)

training:
  epochs: 500               # 训练轮数
  batch_size: 128            # 批次大小
  lr: 0.0001                # 学习率
  device: 'cuda'            # 使用 'cuda' 或 'cpu'
  num_workers: 16            # 数据加载进程数 (根据你的机器调整)
  seed: 42                  # 随机种子

logging:
  log_interval: 1          # 每隔多少 epoch 打印一次详细统计信息